<a href="https://colab.research.google.com/github/zhaocaiQ/machine_learning_study/blob/master/pytorch_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서(tensors)
 #### 넘파이(Numpy)의 ndarray와 유사
 #### GPU를 사용한 연산 가속도 가능

In [1]:
#파이터치 라이브러리
import torch

In [2]:
#버전확인
torch.__version__

'1.10.0+cu111'

In [4]:
#초기화 되지 않은 행렬
x = torch.empty(4, 2)
print(x)

tensor([[2.4450e-01, 3.0663e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30]])


In [5]:
#무작위로 초기화된 행렬
x = torch.rand(4, 2)
print(x)

tensor([[0.7150, 0.6934],
        [0.4583, 0.2476],
        [0.5531, 0.3319],
        [0.3472, 0.2138]])


In [7]:
# dtype이 long, 0으로 채워진 텐서
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [8]:
# 원하는 값으로 텐서 만들기
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [11]:
# 1로 텐서만들기, double은 float64로 나옴
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [12]:
# 기존의 x라는 형태(크기)를 그대로 가져와서 (2, 4) 안의 값만 랜덤하게 채워줌.
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 0.9943,  0.1338,  0.6624,  0.4021],
        [ 1.3480, -0.6067,  1.4737, -1.4247]])


In [13]:
# 텐서의 크기
print(x.size())

torch.Size([2, 4])


In [14]:
# 텐서의 연산

In [17]:
# 덧셈1 +오퍼레이터 이용
y = torch.rand(2, 4)
print(y)
print(x + y)

tensor([[0.9957, 0.8984, 0.7739, 0.3891],
        [0.0285, 0.6456, 0.5135, 0.1738]])
tensor([[ 1.9900,  1.0321,  1.4363,  0.7911],
        [ 1.3765,  0.0390,  1.9872, -1.2509]])


In [19]:
# 덧셈2 add()함수 이용
print(torch.add(x, y))

tensor([[ 1.9900,  1.0321,  1.4363,  0.7911],
        [ 1.3765,  0.0390,  1.9872, -1.2509]])


In [21]:
# 덧셈3 결과 텐서를 인자로 제공
result = torch.empty(2, 4)
torch.add(x, y, out=result) #x와 y를 더한 값을 out으로 result에 할당해줌.
print(result)

tensor([[ 1.9900,  1.0321,  1.4363,  0.7911],
        [ 1.3765,  0.0390,  1.9872, -1.2509]])


In [22]:
# 덧셈4 in-place 방식 ex) y += x 방식과 같음.
print(x)
print(y)
y.add_(x)
print(y)

tensor([[ 0.9943,  0.1338,  0.6624,  0.4021],
        [ 1.3480, -0.6067,  1.4737, -1.4247]])
tensor([[0.9957, 0.8984, 0.7739, 0.3891],
        [0.0285, 0.6456, 0.5135, 0.1738]])
tensor([[ 1.9900,  1.0321,  1.4363,  0.7911],
        [ 1.3765,  0.0390,  1.9872, -1.2509]])


In [23]:
# 그외 연산들

In [27]:
x = torch.Tensor([[1, 3],[5, 7]])
y = torch.Tensor([[2, 4],[6, 8]])

# x에서 y 빼기
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [28]:
x = torch.Tensor([[1, 3],[5, 7]])
y = torch.Tensor([[2, 4],[6, 8]])

# x에서 y 곱셈
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])


In [29]:
x = torch.Tensor([[1, 3],[5, 7]])
y = torch.Tensor([[2, 4],[6, 8]])

# x에서 y 나눗셈
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [30]:
x = torch.Tensor([[1, 3],[5, 7]])
y = torch.Tensor([[2, 4],[6, 8]])

# x에서 y .연산 (행렬 곱셈)
print(torch.mm(x, y))

tensor([[20., 28.],
        [52., 76.]])


In [31]:
# 텐서 조작

In [32]:
# 인덱싱
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [34]:
print(x[:,1])

tensor([3., 7.])


In [35]:
# view -> 텐서의 크기나 모양을 변경
x = torch.randn(4, 5)
y = x.view(20) # 1차원형태로 표현
z = x.view(5, -1) # 5행으로 -1은 있는 값 자동배치
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([5, 4])


In [36]:
# item - 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.1540])
-0.15399405360221863
torch.float32


In [37]:
# 스칼라값 하나만 존재해야 함. -> 2개 있으면 item()함수 사용 불가
# 값 하나 있는 것을 스칼라라고 부름.

x = torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.6968,  0.6578])


ValueError: ignored

In [40]:
# squeeze 차원 축소(제거)
tensor = torch.rand(1, 3, 3)
print(tensor) # 대가로 수 3개
tensor.shape

tensor([[[0.7746, 0.3925, 0.6710],
         [0.0451, 0.7141, 0.3799],
         [0.8377, 0.6894, 0.7772]]])


torch.Size([1, 3, 3])

In [39]:
# 기존 3차원 배열에서 2차원으로 줄임.
t = tensor.squeeze()
print(t) # 대가로 수 2개
print(t.shape)

tensor([[0.0102, 0.5602, 0.2174],
        [0.4388, 0.9222, 0.4280],
        [0.8667, 0.5184, 0.1668]])
torch.Size([3, 3])


In [41]:
# unsqueeze 차원을 증가(생성)
tensor = torch.rand(1, 3, 3)
print(tensor) # 대가로 수 3개
tensor.shape

tensor([[[0.5891, 0.9853, 0.5856],
         [0.6703, 0.3161, 0.2311],
         [0.5776, 0.6013, 0.2395]]])


torch.Size([1, 3, 3])

In [43]:
t = tensor.unsqueeze(dim=0)
print(t) # 대가로 수 4개
print(t.shape)

tensor([[[[0.5891, 0.9853, 0.5856],
          [0.6703, 0.3161, 0.2311],
          [0.5776, 0.6013, 0.2395]]]])
torch.Size([1, 1, 3, 3])


In [44]:
# stack 텐서간 결합
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# cat
#### 텐서를 결합하는 메소드
#### 넘파이의 stack과 유사하지만, 쌓을 dim이 존재해야 함.
##### 예를 들어, 해당 차원을 늘려준 후 결합

In [46]:
a = torch.randn(1,1,3,3)
b = torch.randn(1,1,3,3)
c = torch.cat((a,b), dim=0) #dim은 더할 인덱싱?위치를 선택해서 연결할지 정해주는 것.

print(c)
print(c.size())

tensor([[[[-1.8023, -0.5813,  0.1847],
          [ 1.3585,  0.5543, -0.4161],
          [ 0.2783,  0.4874, -1.6379]]],


        [[[-1.2126, -0.3412,  0.8444],
          [-0.5492, -0.0700, -0.2231],
          [ 0.7113, -1.1228, -1.3494]]]])
torch.Size([2, 1, 3, 3])


In [47]:
a = torch.randn(1,3,3)
b = torch.randn(1,3,3)
c = torch.cat((a,b), dim=0)

print(c)
print(c.size())

tensor([[[ 0.9898,  0.0791,  0.1833],
         [-0.8203,  0.8161, -0.8315],
         [ 0.0078,  0.2916,  1.1305]],

        [[ 1.2568, -0.7672,  0.6833],
         [-0.6068, -1.7138, -0.6152],
         [-0.7013,  0.7311,  0.2035]]])
torch.Size([2, 3, 3])


# chunk
#### 텐서를 여러 개로 나눌 때 사용
#### 몇 개의 텐서로 나눌 것이냐

In [50]:
tensor = torch.rand(3,6)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1) # chunk의 중간 매개변수는 몇개로 텐서를 나눌 것이냐

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.5980, 0.8907, 0.6222, 0.5296, 0.0914, 0.4992],
        [0.3410, 0.7975, 0.3271, 0.1205, 0.0669, 0.9109],
        [0.4541, 0.4831, 0.6972, 0.9798, 0.7103, 0.1923]])
tensor([[0.5980, 0.8907],
        [0.3410, 0.7975],
        [0.4541, 0.4831]])
tensor([[0.6222, 0.5296],
        [0.3271, 0.1205],
        [0.6972, 0.9798]])
tensor([[0.0914, 0.4992],
        [0.0669, 0.9109],
        [0.7103, 0.1923]])


# split
#### chunk와 동일한 기능이지만 조금 다름
#### 하나의 텐서당 크기가 얼마이냐

In [51]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1) # split의 중간 매개변수는 하나의 텐서당 몇개의 크기로 나눌 것이냐
print(tensor)
print(t1)
print(t2)

tensor([[0.2327, 0.0532, 0.7066, 0.2201, 0.5310, 0.6894],
        [0.1394, 0.1902, 0.3813, 0.4134, 0.8051, 0.1068],
        [0.5262, 0.2082, 0.2556, 0.0487, 0.5640, 0.1305]])
tensor([[0.2327, 0.0532, 0.7066],
        [0.1394, 0.1902, 0.3813],
        [0.5262, 0.2082, 0.2556]])
tensor([[0.2201, 0.5310, 0.6894],
        [0.4134, 0.8051, 0.1068],
        [0.0487, 0.5640, 0.1305]])
